### ISSUE TITLE
libpng 1.6.28, zlib 1.2.10

### ISSUE THREAD

**Issue by Jan-E** [winlibs/libpng#1]
@weltling 
I tried to compile libpng 1.6.28 and ran into this error:

`libpng_a.lib(pngrutil.obj) : error LNK2001: unresolved external symbol _inflateReset2
`

Then I noticed there has been an update in Zlib:
http://www.libpng.org/pub/png/png2017.html

We do not have to overrush, but updating zlib might be a thing to consider.

**Comment by weltling** [comment]
Thanks for the ping @Jan-E. Zlib can be updated for master, but yet too early, given we've seen two consequent releases short in time one after the other. But also, zlib is the base for quite some other deps and PECL exts, so definitely not for stable branches. Otherwise, nothing urgent for force an action right now.

Thanks.

**Comment by Jan-E** [comment]
Thanks.
